add nvidia driver installation support.

diff --git a/core/controlplane/config/templates/cloud-config-worker b/core/controlplane/config/templates/cloud-config-worker
--- a/core/controlplane/config/templates/cloud-config-worker
+++ b/core/controlplane/config/templates/cloud-config-worker
@@ -180,6 +180,10 @@ coreos:
         {{if .UseCalico -}}
         ExecStartPre=/usr/bin/docker run --rm -e SLEEP=false -v /opt/cni/bin:/host/opt/cni/bin {{ .CalicoCniImage.RepoWithTag }} /install-cni.sh
         {{end -}}
+        {{ if .Gpu.Nvidia.IsEnabledOn .InstanceType -}}
+        ExecStartPre=/opt/nvidia-build/build-and-install.sh
+        TimeoutStartSec=900
+        {{ end -}}
         ExecStart=/usr/lib/coreos/kubelet-wrapper \
         --cni-conf-dir=/etc/kubernetes/cni/net.d \
         {{/* Work-around until https://github.com/kubernetes/kubernetes/issues/43967 is fixed via https://github.com/kubernetes/kubernetes/pull/43995 */ -}}
@@ -205,6 +209,9 @@ coreos:
         --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem \
         {{- end }}
         --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
+        {{- if .Gpu.Nvidia.IsEnabledOn .InstanceType }}
+        --feature-gates="Accelerators=true" \
+        {{- end }}
         --require-kubeconfig \
         $KUBELET_OPTS
         Restart=always
@@ -852,4 +859,415 @@ write_files:
   - path: /etc/kubernetes/auth/kubelet-bootstrap.token{{if .AssetsEncryptionEnabled}}.enc{{end}}
     encoding: gzip+base64
     content: {{.AuthTokensConfig.KubeletBootstrapToken}}
+{{ end }}
+
+{{ if .Gpu.Nvidia.IsEnabledOn .InstanceType }}
+  - path: /opt/nvidia-build/README
+    owner: root:root
+    permissions: 0644
+    content: |
+      Most of scripts in this directory are borrowed from https://github.com/Clarifai/coreos-nvidia/
+      Especially from https://github.com/Clarifai/coreos-nvidia/pull/4
+      
+  - path: /opt/nvidia-build/LICENSE
+    owner: root:root
+    permissions: 0644
+    content: |
+      Please see https://github.com/Clarifai/coreos-nvidia/
+
+  - path: /opt/nvidia-build/build-and-install.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #! /bin/bash
+      set -e
+      function is_gpu_enabled(){
+        local instance_type=$1
+        [[ -n $instance_type ]] && ([[ $instance_type == p2* ]] || [[ $instance_type ==  g2* ]])
+      }
+
+      INSTANCE_TYPE=$(curl -s http://169.254.169.254/latest/meta-data/instance-type)
+
+      if is_gpu_enabled $INSTANCE_TYPE; then
+        MOD_INSTALLED=$(lsmod | grep nvidia | wc -l)
+        if [[ $MOD_INSTALLED -lt 0 ]] || [[ ! -e /opt/nvidia/current ]]; then
+          cd /opt/nvidia-build/
+          bash -x build.sh {{.Gpu.Nvidia.Version}}
+          bash -x nvidia-install.sh {{.Gpu.Nvidia.Version}}
+          /usr/bin/systemctl is-active nvidia-start.service
+        else
+          echo "Nvidia drivers seems to be installed already. Skipped."
+        fi
+      else
+        echo "GPU is NOT supported in $INSTANCE_TYPE. Nvidia drivers won't build nor install."
+      fi
+
+  - path: /opt/nvidia-build/71-nvidia.rules
+    owner: root:root
+    permissions: 0644
+    content: |
+      # Tag the device as master-of-seat so that logind is happy
+      # (see LP: #1365336)
+      SUBSYSTEM=="pci", ATTRS{vendor}=="0x10de", DRIVERS=="nvidia", TAG+="seat", TAG+="master-of-seat"
+
+      # Start and stop nvidia-persistenced on power on and power off
+      # respectively
+      ACTION=="add" DEVPATH=="/bus/acpi/drivers/NVIDIA ACPI Video Driver" SUBSYSTEM=="drivers" RUN+="/bin/systemctl start --no-block nvidia-persistenced.service"
+      ACTION=="remove" DEVPATH=="/bus/acpi/drivers/NVIDIA ACPI Video Driver" SUBSYSTEM=="drivers" RUN+="/bin/systemctl stop --no-block nvidia-persistenced"
+
+      # Start and stop nvidia-persistenced when loading and unloading
+      # the driver
+      ACTION=="add" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/bin/systemctl start --no-block nvidia-persistenced.service"
+      ACTION=="remove" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/bin/systemctl stop --no-block nvidia-persistenced"
+
+      # Load and unload nvidia-modeset module
+      ACTION=="add" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/opt/nvidia/current/bin/nvidia-insmod.sh nvidia-modeset.ko"
+      ACTION=="remove" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/usr/sbin/rmmod -r nvidia-modeset"
+
+      # Load and unload nvidia-drm module
+      ACTION=="add" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/opt/nvidia/current/bin/nvidia-insmod.sh nvidia-drm.ko"
+      ACTION=="remove" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/usr/sbin/rmmod nvidia-drm"
+
+      # Load and unload nvidia-uvm module
+      ACTION=="add" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/opt/nvidia/current/bin/nvidia-insmod.sh nvidia-uvm.ko"
+      ACTION=="remove" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/usr/sbin/rmmod -r nvidia-uvm"
+
+      # This will create the device nvidia device nodes
+      ACTION=="add" DEVPATH=="/module/nvidia" SUBSYSTEM=="module" RUN+="/opt/nvidia/current/bin/nvidia-smi"
+
+      # Create the device node for the nvidia-uvm module
+      ACTION=="add" DEVPATH=="/module/nvidia_uvm" SUBSYSTEM=="module" RUN+="/opt/nvidia/current/bin/create-uvm-dev-node.sh"
+
+  - path: /opt/nvidia-build/_container_build.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/sh
+
+      # Default: use binary packages instead of building everything from source
+      EMERGE_SOURCE_FLAGS=gK
+      while :; do
+        case $1 in
+          --emerge-sources)
+            EMERGE_SOURCE_FLAGS=
+            ;;
+          *)
+            break
+        esac
+        shift
+      done
+
+
+      VERSION=$1
+      echo Building ${VERSION}
+
+      function finish {
+        cat /nvidia_installers/NVIDIA-Linux-x86_64-${VERSION}/nvidia-installer.log
+      }
+
+      set -e
+      trap finish exit
+
+      emerge-gitclone
+      . /usr/share/coreos/release
+      git -C /var/lib/portage/coreos-overlay checkout build-${COREOS_RELEASE_VERSION%%.*}
+      emerge -${EMERGE_SOURCE_FLAGS}q --jobs 4 --load-average 4 coreos-sources
+
+      cd /usr/src/linux
+      cp /lib/modules/*-coreos*/build/.config .config
+
+      make olddefconfig
+      make modules_prepare
+
+      cd /nvidia_installers/NVIDIA-Linux-x86_64-${VERSION}
+      ./nvidia-installer -s -n --kernel-source-path=/usr/src/linux \
+        --no-check-for-alternate-installs --no-opengl-files \
+        --kernel-install-path=${PWD} --log-file-name=${PWD}/nvidia-installer.log
+
+  - path: /opt/nvidia-build/_export.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/sh
+
+      set -e
+
+      ARTIFACT_DIR=$1
+      VERSION=$2
+      COMBINED_VERSION=$3
+
+      TOOLS="nvidia-debugdump nvidia-cuda-mps-control nvidia-xconfig nvidia-modprobe nvidia-smi nvidia-cuda-mps-server
+      nvidia-persistenced nvidia-settings"
+
+      # Create archives with no paths
+      tar -C ${ARTIFACT_DIR} -cvj $(basename -a ${ARTIFACT_DIR}/*.so.*) > libraries-${VERSION}.tar.bz2
+      tar -C ${ARTIFACT_DIR} -cvj ${TOOLS} > tools-${VERSION}.tar.bz2
+      tar -C ${ARTIFACT_DIR}/kernel -cvj $(basename -a ${ARTIFACT_DIR}/kernel/*.ko) > modules-${COMBINED_VERSION}.tar.bz2
+
+  - path: /opt/nvidia-build/build.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/bash
+      #
+      # Build NVIDIA drivers for a given CoreOS version
+      #
+
+      KEEP_CONTAINER=false
+      EMERGE_SOURCES=""
+      while :; do
+        case $1 in
+          --keep)
+            KEEP_CONTAINER=true
+            ;;
+          --emerge-sources)
+            EMERGE_SOURCES=$1
+            ;;
+          -?*)
+            echo Unknown flag $1
+            exit 1
+            ;;
+          *)
+            break
+        esac
+        shift
+      done
+
+      echo "Keeping container around after build: ${KEEP_CONTAINER}"
+      echo "Additional flags: ${EMERGE_SOURCES}"
+
+      # If we are on CoreOS by default build for the current CoreOS version
+      if [[ -f /etc/lsb-release && -f /etc/coreos/update.conf ]]; then
+          source /etc/lsb-release
+          source /etc/coreos/update.conf
+
+          COREOS_TRACK_DEFAULT=$GROUP
+          COREOS_VERSION_DEFAULT=$DISTRIB_RELEASE
+      fi
+
+      DRIVER_VERSION=${1:-{{.Gpu.Nvidia.Version}}}
+      COREOS_TRACK=${2:-$COREOS_TRACK_DEFAULT}
+      COREOS_VERSION=${3:-$COREOS_VERSION_DEFAULT}
+
+      DRIVER_ARCHIVE=NVIDIA-Linux-x86_64-${DRIVER_VERSION}
+      DRIVER_ARCHIVE_PATH=${PWD}/nvidia_installers/${DRIVER_ARCHIVE}.run
+      DEV_CONTAINER=coreos_developer_container.bin.${COREOS_VERSION}
+      WORK_DIR=pkg/run_files/${COREOS_VERSION}
+      ORIGINAL_DIR=${PWD}
+
+      function onerr {
+        echo Caught error
+        finish
+      }
+
+      function onexit {
+        finish
+      }
+
+      function finish {
+        if [ "${KEEP_CONTAINER}" != "true" ]
+        then
+          cd ${ORIGINAL_DIR}
+          echo Cleaning up
+          sudo rm -Rf ${DEV_CONTAINER} ${WORK_DIR}/${DRIVER_ARCHIVE} tmp
+        fi
+        exit
+      }
+
+      set -e
+      trap onerr ERR
+      trap onexit exit
+
+      if [ ! -f ${DEV_CONTAINER} ]
+      then
+        echo Downloading CoreOS ${COREOS_TRACK} developer image ${COREOS_VERSION}
+        SITE=${COREOS_TRACK}.release.core-os.net/amd64-usr
+        curl -s -L https://${SITE}/${COREOS_VERSION}/coreos_developer_container.bin.bz2 \
+          -z ${DEV_CONTAINER}.bz2 \
+          -o ${DEV_CONTAINER}.bz2
+        echo Decompressing
+        bunzip2 -k ${DEV_CONTAINER}.bz2
+      fi
+
+      if [ ! -f ${DRIVER_ARCHIVE_PATH} ]
+      then
+        echo Downloading NVIDIA Linux drivers version ${DRIVER_VERSION}
+        mkdir -p nvidia_installers
+        SITE=us.download.nvidia.com/XFree86/Linux-x86_64
+        curl -s -L http://${SITE}/${DRIVER_VERSION}/${DRIVER_ARCHIVE}.run \
+          -z ${DRIVER_ARCHIVE_PATH} \
+          -o ${DRIVER_ARCHIVE_PATH}
+      fi
+
+      rm -Rf ${PWD}/tmp
+      mkdir -p ${PWD}/tmp ${WORK_DIR}
+      cp -ul ${DRIVER_ARCHIVE_PATH} ${WORK_DIR}
+
+      cd ${WORK_DIR}
+      chmod +x ${DRIVER_ARCHIVE}.run
+      sudo rm -Rf ./${DRIVER_ARCHIVE}
+      ./${DRIVER_ARCHIVE}.run -x -s
+      cd ${ORIGINAL_DIR}
+
+      systemd-nspawn -i ${DEV_CONTAINER} \
+        --bind=${PWD}/_container_build.sh:/build.sh \
+        --bind=${PWD}/${WORK_DIR}:/nvidia_installers \
+        /bin/bash -x /build.sh ${EMERGE_SOURCES} ${DRIVER_VERSION} || echo "nspawn fails as expected.  Because kernel modules can't install in the container"
+
+      sudo chown -R ${UID}:${GROUPS[0]} ${PWD}/${WORK_DIR}
+
+      bash -x _export.sh ${WORK_DIR}/*-${DRIVER_VERSION} \
+        ${DRIVER_VERSION} ${COREOS_VERSION}-${DRIVER_VERSION}
+
+  - path: /opt/nvidia-build/create-uvm-dev-node.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/sh
+      # This script is borrowed from https://github.com/Clarifai/coreos-nvidia/pull/4
+      # Get the major device number for nvidia-uvm and create the node
+      echo "Set up NVIDIA UVM"
+      major=`grep nvidia-uvm /proc/devices | awk '{print $1}'`
+      if [ -n "$major" ]; then
+          mknod -m 666 /dev/nvidia-uvm c $major 0
+      fi
+
+  - path: /opt/nvidia-build/nvidia-insmod.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/sh
+      # This script is borrowed from https://github.com/Clarifai/coreos-nvidia/pull/4
+      /usr/sbin/insmod /opt/nvidia/current/lib/modules/$(uname -r)/video/$1
+
+  - path: /opt/nvidia-build/nvidia-persistenced.service
+    owner: root:root
+    permissions: 0644
+    content: |
+      [Unit]
+      Description=NVIDIA Persistence Daemon
+      Wants=local-fs.target
+
+      [Service]
+      Type=forking
+      ExecStart=/opt/nvidia/current/bin/nvidia-persistenced --user nvidia-persistenced --no-persistence-mode --verbose
+      ExecStopPost=/bin/rm -rf /var/run/nvidia-persistenced
+
+  - path: /opt/nvidia-build/nvidia-start.service
+    owner: root:root
+    permissions: 0644
+    content: |
+      [Unit]
+      Description=Load NVIDIA module
+      After=local-fs.target
+
+      [Service]
+      Type=oneshot
+      RemainAfterExit=true
+      ExecStart=/opt/nvidia/current/bin/nvidia-start.sh
+
+      [Install]
+      WantedBy=multi-user.target
+
+  - path: /opt/nvidia-build/nvidia-start.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/sh
+      # This script is borrowed from https://github.com/Clarifai/coreos-nvidia/pull/4
+
+      /opt/nvidia/current/bin/nvidia-insmod.sh nvidia.ko
+
+      # Start the first devices
+      /usr/bin/mknod -m 666 /dev/nvidiactl c 195 255 2>/dev/null
+      NVDEVS=`lspci | grep -i NVIDIA`
+      N3D=`echo "$NVDEVS" | grep "3D controller" | wc -l`
+      NVGA=`echo "$NVDEVS" | grep "VGA compatible controller" | wc -l`
+      N=`expr $N3D + $NVGA - 1`
+      for i in `seq 0 $N`; do
+        mknod -m 666 /dev/nvidia$i c 195 $i
+      done
+
+      /opt/nvidia/current/bin/set-gpu-name-to-kubelet-opts.sh
+
+  - path: /opt/nvidia-build/set-gpu-name-to-kubelet-opts.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/bash
+      # Register GPU model name to node label
+      # Currently, we assume all GPU devices in a node are homogeneous (the same model).
+      [ -e /etc/default/kubelet ] || echo "KUBELET_OPTS=\"\"" > /etc/default/kubelet
+      source /etc/default/kubelet
+      if [ ! "$KUBELET_OPTS" == *nvidia-gpu-name* ]; then
+        NVIDIA_GPU_NAME=$(/opt/nvidia/current/bin/nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -E 's/ +/_/g')
+        KUBELET_OPTS="--node-labels='alpha.kubernetes.io/nvidia-gpu-name=$NVIDIA_GPU_NAME' $KUBELET_OPTS"
+        KUBELET_OPTS="--node-labels='kube-aws.coreos.com/gpu=nvidia' $KUBELET_OPTS"
+        KUBELET_OPTS="--node-labels='kube-aws.coreos.com/nvidia-gpu-version={{.Gpu.Nvidia.Version}}' $KUBELET_OPTS"
+        echo "KUBELET_OPTS=\"$KUBELET_OPTS\"" > /etc/default/kubelet
+      fi
+
+  - path: /opt/nvidia-build/nvidia-install.sh
+    owner: root:root
+    permissions: 0755
+    content: |
+      #!/bin/bash
+      # This script is borrowed from https://github.com/Clarifai/coreos-nvidia/pull/4
+
+      if [[ $(uname -r) != *"-coreos"* ]]; then
+          echo "OS is not CoreOS"
+          exit 1
+      fi
+
+      # If we are on CoreOS by default use the current CoreOS version
+      if [[ -f /etc/lsb-release && -f /etc/coreos/update.conf ]]; then
+          source /etc/lsb-release
+          source /etc/coreos/update.conf
+
+          COREOS_TRACK_DEFAULT=$GROUP
+          COREOS_VERSION_DEFAULT=$DISTRIB_RELEASE
+          if [[ $DISTRIB_ID != *"CoreOS"* ]]; then
+              echo "Distribution is not CoreOS"
+              exit 1
+          fi
+      fi
+
+      DRIVER_VERSION=${1:-{{.Gpu.Nvidia.Version}}}
+      COREOS_TRACK=${2:-$COREOS_TRACK_DEFAULT}
+      COREOS_VERSION=${3:-$COREOS_VERSION_DEFAULT}
+
+      # this is where the modules go
+      release=$(uname -r)
+
+      mkdir -p /opt/nvidia/$DRIVER_VERSION/lib64 2>/dev/null
+      mkdir -p /opt/nvidia/$DRIVER_VERSION/bin 2>/dev/null
+      ln -sfT lib64 /opt/nvidia/$DRIVER_VERSION/lib 2>/dev/null
+      mkdir -p /opt/nvidia/$DRIVER_VERSION/lib64/modules/$release/video/
+
+      tar xvf libraries-$DRIVER_VERSION.tar.bz2 -C /opt/nvidia/$DRIVER_VERSION/lib64/
+      tar xvf modules-$COREOS_VERSION-$DRIVER_VERSION.tar.bz2 -C /opt/nvidia/$DRIVER_VERSION/lib64/modules/$release/video/
+      tar xvf tools-$DRIVER_VERSION.tar.bz2 -C /opt/nvidia/$DRIVER_VERSION/bin/
+
+      install -m 755 create-uvm-dev-node.sh /opt/nvidia/$DRIVER_VERSION/bin/
+      install -m 755 nvidia-start.sh /opt/nvidia/$DRIVER_VERSION/bin/
+      install -m 755 nvidia-insmod.sh /opt/nvidia/$DRIVER_VERSION/bin/
+      install -m 755 set-gpu-name-to-kubelet-opts.sh /opt/nvidia/$DRIVER_VERSION/bin/
+      ln -sfT $DRIVER_VERSION /opt/nvidia/current 2>/dev/null
+
+      cp -f 71-nvidia.rules /etc/udev/rules.d/
+      udevadm control --reload-rules
+
+      mkdir -p /etc/ld.so.conf.d/ 2>/dev/null
+      echo "/opt/nvidia/current/lib64" > /etc/ld.so.conf.d/nvidia.conf
+      ldconfig
+
+      echo "Configuring nvidia persistence user"
+      id -u nvidia-persistenced >/dev/null 2>&1 || \
+      useradd --system --home '/' --shell '/sbin/nologin' -c 'NVIDIA Persistence Daemon' nvidia-persistenced
+
+      cp *.service /etc/systemd/system/
+      systemctl daemon-reload
+      systemctl enable nvidia-start.service
+      systemctl start nvidia-start.service
+
 {{ end }}
